name: 'commit-range-action'
description: |
  Action for determining updated commit ranges based on workflow's event payloads.
branding:
  icon: git-pull-request
  color: blue
outputs:
  commit-range:
    description: 'Determined commit range'
  begin-sha:
    description: 'Begin of the commit range'
  end-sha:
    description: 'End of the commit range'
  fetch-depth:
    description: 'Number of commits in the commit range'
runs:
  using: 'node20'
  main: './dist/index.js'
